export type { Countries } from './countries.interface'
export type { QuestionDataAnswer } from './questionDataAnswer.interface'
export type { CurrentQuestion } from './currentQuestion.interface'
export type { CountryUserQuestion } from './countryUserQuestion.interface'
export type { AllSavedAnswer } from './allSavedAnswer.interface'
