export type { Countries } from './country.interface'
export type { QuestionDataAnswer } from './questionDataAnswer.interface'
export type { CurrentQuestion } from './currentQuestion.interface'
export type { GenerateCountriesInformation } from './generateCountriesInformation.interface'
export type { AllSavedAnswer } from './allSavedAnswer.interface'
