export const countryActionTypes = {
    GET_COUNTRY: 'GET_COUNTRY',
    SET_GENERATE_COUNTRY_INFORMATION: 'SET_GENERATE_COUNTRY_INFORMATION',
    SET_COUNTER: 'SET_COUNTER',
    GET_CURRENT_QUESTION: 'GET_CURRENT_QUESTION',
    GENERATE_ANSWERS: 'GENERATE_ANSWERS',
    DELETE_DATA: 'DELETE_DATA'
}

