import { deleteAllDataIncludeDataAfterResult } from './actions'

export const countriesActionTypes = {
  GET_COUNTRIES: 'GET_COUNTRIES',
  SET_GENERATE_COUNTRIES_INFORMATION: 'SET_GENERATE_COUNTRIES_INFORMATION',
  SET_COUNTER: 'SET_COUNTER',
  GET_CURRENT_QUESTION: 'GET_CURRENT_QUESTION',
  GENERATE_ANSWERS: 'GENERATE_ANSWERS',
  DELETE_DATA: 'DELETE_DATA',
  CHOOSE_BY_USER_ANSWER: 'CHOOSE_BY_USER_ANSWER',
  SAVE_ALL_ANSWERS: 'SAVE_ALL_ANSWERS',
  SAVE_CORRECT_ANSWER: 'SAVE_CORRECT_ANSWER',
  NAME_QUESTION: 'NAME_QUESTION',
  DELETE_DATA_INCLUDE_DATA_AFTER_RESULT: 'DELETE_DATA_INCLUDE_DATA_AFTER_RESULT'
}
