export const countriesActionTypes = {
  GET_COUNTRIES: 'GET_COUNTRIES',
  SET_GENERATE_COUNTRIES_INFORMATION: 'SET_GENERATE_COUNTRIES_INFORMATION',
  SET_COUNTER: 'SET_COUNTER',
  GET_CURRENT_QUESTION: 'GET_CURRENT_QUESTION',
  GENERATE_ANSWERS: 'GENERATE_ANSWERS',
  DELETE_DATA: 'DELETE_DATA'
}
