export const FLAG_ROUT: string = '/flag-quiz'
export const COUNTRY_ROUT: string = '/country-quiz'
export const MAIN: string = '/'
export const RESULTS: string = '/results'
export const SHOW_RESULT_QUIZ_ROUT: string = '/show-result-quiz'
