export const FLAG_ROUT: string = '/flag-quiz'
export const COUNTRY_ROUT: string = '/country-quiz'
export const COUNTRY_QUIZ_ROUT: string = '/country-quiz-flag-or-capital'
export const RESULTS: string = '/results'
export const SHOW_RESULT_QUIZ_ROUT: string = '/show-result-quiz'
export const MAIN: string = '/'
